
# 单行注释

print("hello python")

print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
sma
print("hello python")
print("hello python")
print("hello word")
print("hello wore +1 ")

rint("hello python")
print("hello wore +1 ")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("hello python")
print("注释之后")
print("nihaoyezaijia")
